apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: "myapp.local"   # âœ… Change this from IP to DNS name
    http:
      paths:
      - path: /user
        pathType: Prefix
        backend:
          service:
            name: user
            port:
              number: 3000
      - path: /product
        pathType: Prefix
        backend:
          service:
            name: product
            port:
              number: 3000
      - path: /payment
        pathType: Prefix
        backend:
          service:
            name: payment
            port:
              number: 3000
      - path: /order
        pathType: Prefix
        backend:
          service:
            name: order
            port:
              number: 3000
